### ISSUE TITLE
Suddenly stopped working, help

### ISSUE THREAD

**Issue by Silica-Anima** [KohakuBlueleaf/Kohaku-NAI#11]
Traceback (most recent call last):
      File "...\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "...\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "...\stable-diffusion-webui\modules\txt2img.py", line 107, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "...\stable-diffusion-webui\modules\scripts.py", line 766, in run
        processed = script.run(p, *script_args)
      File "...\stable-diffusion-webui\extensions\Kohaku-NAI\scripts\kohaku-nai.py", line 186, in run
        raise Exception("Failed to generate image: " + str(failed_img_data))
    Exception: Failed to generate image: Generation failed

Extension suddenly stopped working yesterday, tried -
Delete and reinstall extension
Downloaded another a1111 with fresh extension install

Did not work. NAI side generation is normal, regular txt2img in a1111 functions normally too.

**Comment by KohakuBlueleaf** [comment]
https://github.com/KohakuBlueleaf/Kohaku-NAI/pull/10
update it.

**Comment by Silica-Anima** [comment]
Thanks. All green now.
