### ISSUE TITLE
Internal Server Error often occurs in Server mode | Server 模式下经常出现 Internal Server Error

### ISSUE THREAD

**Issue by WallBreakerNO4** [KohakuBlueleaf/Kohaku-NAI#15]
I used the local Stable Diffusion webui to install the plug-in, and Kohaku-NAI ran server mode on another server to use this project. When I generate images, the generation often fails due to Internal Server Error. The following is the error:

我使用本地 Stable Diffusion webui 安装插件，Kohaku-NAI 在另一台服务器上运行服务器模式的方式来使用本项目。在我生成图片时，经常出现 Internal Server Error 导致的生成失败，以下是报错：

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/curl_cffi/requests/session.py", line 1147, in request
    await task
curl_cffi.curl.CurlError: Failed to perform, curl: (18) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/wall/Kohaku-NAI/kohaku_nai/server.py", line 216, in gen
    img_bytes, json_payload = await generate_novelai_image(
  File "/home/wall/Kohaku-NAI/kohaku_nai/utils.py", line 237, in generate_novelai_image
    response = await client.post(f"{API_IMAGE_URL}/ai/generate-image", json=payload)
  File "/home/wall/Kohaku-NAI/venv/lib/python3.10/site-packages/curl_cffi/requests/session.py", line 1152, in request
    raise RequestsError(str(e), e.code, rsp) from e
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (18) . See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

At first, I suspected that it was due to interference in the mainland China network, but the error occurs whether deploying the service with a proxy to access NAI in my homelab or directly deploying it on servers outside the mainland. Additionally, I found that when the batch size is increased, this error occurs more frequently.

I am not familiar with network programming, but after looking up the error code for curl, it indicates that the error is caused by a mismatch between the file size and the expected size. Please refer to <https://curl.se/libcurl/c/libcurl-errors.html> for more details.

Could you please clarify if this is a bug or if it is due to limitations of the NovelAI API?

我最开始怀疑是因为我在中国大陆网络有干扰导致的，但无论是在自己的homelab上部署服务外加代理访问 NAI，还是直接在非大陆的服务器上部署，都会有这个报错。此外我发现，当 Batch_size 调高时，更容易出现这个报错。

我对网络编程不了解，但我查了一下 curl 的报错代码，说是文件大小与预期不一致导致的。 <https://curl.se/libcurl/c/libcurl-errors.html>

请问这是个 BUG 吗？还是由于 NovelAI API 的限制导致的？

**Comment by KohakuBlueleaf** [comment]
don't use curl_cffi backend unless you actually need it
switch to httpx should solve this
